# -*- coding: utf-8 -*-
"""shadow_garden.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11J_Hf2kueUmLyuKk-hQS1F923nCwG5tQ
"""

import streamlit as st
import json
import os
import hashlib

# Helper to hash passwords
def hash_password(password):
    return hashlib.sha256(password.encode()).hexdigest()

# Load user data
def load_users():
    if not os.path.exists("users.json"):
        return {}
    with open("users.json", "r") as f:
        return json.load(f)

# Save user data
def save_users(users):
    with open("users.json", "w") as f:
        json.dump(users, f)

# Background music with HTML
def add_background_music():
    st.markdown("""
        <audio autoplay loop>
          <source src="https://www.bensound.com/bensound-music/bensound-sunny.mp3" type="audio/mpeg">
        </audio>
        """, unsafe_allow_html=True)

# Main app
def main():
    st.set_page_config(page_title="THE FOREST OF FEELS", layout="centered")

    st.title("🌸 Welcome to The Shadow Garden Game 🌸")
    st.markdown("Relax, breathe, and choose your path... 🌿✨")

    # ⬇️ Add your local GIF and background music here
    st.image("https://raw.githubusercontent.com/Sanskruti711/forest-of-feels/main/door.gif", width=850)
    st.audio("https://raw.githubusercontent.com/Sanskruti711/forest-of-feels/main/music.mp3")



    users = load_users()

    tab1, tab2 = st.tabs(["🔐 Login", "🌈 Signup"])
    
    ...


    with tab1:
        username = st.text_input("Username")
        password = st.text_input("Password", type="password")

        if st.button("Login"):
            if username in users and users[username] == hash_password(password):
                st.success(f"Welcome back, {username} 🌟")
                st.session_state["logged_in_user"] = username
                st.session_state["page"] = "main"
            else:
                st.error("Wrong username or password.")

    with tab2:
        new_username = st.text_input("Create a fun username")
        new_password = st.text_input("Create a fun password", type="password")

        if st.button("Signup"):
            if new_username in users:
                st.warning("Username already exists. Try another!")
            else:
                users[new_username] = hash_password(new_password)
                save_users(users)
                st.success("Signed up successfully! Now login.")

if __name__ == "__main__":
    main()
